name: ISS Tracker Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:      # Allows you to click a button to test it manually

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          # This maps your Secrets to the script's Environment Variables
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          USER_LATITUDE: ${{ secrets.USER_LATITUDE }}
          USER_LONGITUDE: ${{ secrets.USER_LONGITUDE }}
        run: python main.
